cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'

cask 'atom-beta'
cask 'bittorrent'
cask 'dash'
cask 'docker-edge'
cask 'dropbox'
cask 'firefox'
cask 'github-desktop'
cask 'google-chrome'
cask 'hyper'
cask 'lastpass'
cask 'slack'
cask 'tunnelbear'
cask 'vlc'
